### ISSUE TITLE
broken Status links for core contributors

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/nimbus.status.im#16]
The first part of the URL is duplicated: https://get.status.im/user/https://get.status.im/user/0x04f05d31956e9c918c35c30defe1ab69bc693d27eb3f79d619c3ba4f9f044b2349a79fb38e3a614ce9af1286910aa19bf24b53c18d48e10657cbf615a380928f6e

**Comment by Swader** [comment]
Thank you! Fixed
