### ISSUE TITLE
swig partials breaking site UI

### ISSUE THREAD

**Issue by samthomson** [status-im/nimbus.status.im#29]
This site uses swig templates, like the shared partials used to. The shared partials were recently updated to ejs along with the status.im website. Although this site was not updated, but since it still uses the partials (which are now ejs), it looks funny. (note, it only looks funny if the submodule dep is updated, it will build ok if left as it is, but that means being prevented from getting updated content from newer versions of the partials).
Header:
![image](https://user-images.githubusercontent.com/6588340/51102629-4c4b6c00-1812-11e9-9a48-45b9adef2f5c.png)
footer:
![image](https://user-images.githubusercontent.com/6588340/51102632-51a8b680-1812-11e9-8df1-aeb0a5a4e158.png)

I pointed this out here: https://github.com/status-im/status.im-partials/pull/4#issuecomment-452256279

And so am going to submit a PR on this repo. (Just making this issue for context, to submit the PR against).

**Comment by andytudhope** [comment]
Sure thing - here was the original issue (for Nunjucks support, but turned out it didn't quite work as expected): https://github.com/status-im/status.im/issues/135 was where it started, continued in https://github.com/status-im/status.im/issues/156

**Comment by samthomson** [comment]
solved by https://github.com/status-im/nimbus.status.im/pull/30

**Comment by Swader** [comment]
Nice 🤘
